### ISSUE TITLE
S-Bahn Halterstellen außerhalb München funktionieren nicht

### ISSUE THREAD

**Issue by FaserF** [rmoriz/mvg-live#9]
Funktionieren lediglich die Stationen im Landkreis München?
Ich würde gern die Abfahrtszeiten von Zorneding, Eglharting, Starnberg nutzen. Allerdings ist die "nächste" Station die wieder funktioniert erst "Haar" welches im Landkreis München ist. Den Rest findet es nicht.

Außerdem hätte ich noch eine Frage: 
Werden Verspätungen auch mit einberechnet?

**Comment by rmoriz** [comment]
Nur Daten von der MVG. S-Bahn-Daten kamen viel später, müssen auf https://reiseauskunft.bahn.de/bin/bhftafel.exe/dn?ld=39208&protocol=https:&rt=1 gescraped werdern (oder eine der anderen HAFAS-Interfaces).

**Comment by FaserF** [comment]
Danke für die Antwort.
Was genau meinst du gescraped? 
Die Antwort oben bedeutet dass Sbahn Daten nicht möglich sind mit deinem Tool? Ich finde nur interessant, dass bei "Haar" z,b. S-Bahnen angezeigt werden, nur außerhalb werden die Stationen eben nicht mehr gefunden.
